# Generated by Django 4.2 on 2024-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.DecimalField(decimal_places=3, default=2.0, editable=False, max_digits=8, verbose_name='"Size (MB)"'),
            preserve_default=False,
        ),
    ]
