import os

REDIS_HOST = os.environ.get('REDIS_HOST', 'redis')

CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':6379/0'
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':6379/0'

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 24 * 60 * 60}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 5
